name: Build Godot APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Godot Export Templates
      run: |
        curl -L https://downloads.tuxfamily.org/godotengine/3.6/beta5/Godot_v3.6-beta5_export_templates.tpz -o godot-templates.tpz

    - name: Extract Godot Export Templates
      run: |
        mkdir -p ~/.local/share/godot/templates/3.6.beta5
        unzip godot-templates.tpz -d ~/godot-templates
        mv ~/godot-templates/templates/* ~/.local/share/godot/templates/3.6.beta5/
        rm -rf ~/godot-templates

    - name: Download and Install Godot Headless
      run: |
        wget https://downloads.tuxfamily.org/godotengine/3.6/beta5/Godot_v3.6-beta5_linux_headless.64.zip
        unzip Godot_v3.6-beta5_linux_headless.64.zip
        sudo mv Godot_v3.6-beta5_linux_headless.64 /usr/local/bin/godot
        chmod +x /usr/local/bin/godot

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30.0.3'
        ndk-version: '25.2.9519653'

    - name: Generate Debug Keystore
      run: |
        keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass vEry2sEcrEtpAsswOrd -keypass vEry2sEcrEtpAsswOrd -dname "CN=Android Debug,O=Android,C=US"

    - name: Build APK
      run: |
        mkdir -p export/android
        /usr/local/bin/godot --export "Android" export/android/IAP.apk
